site_name: Tshoot
site_description: A simple CLI commands to try troubleshooting errors with LLMs

repo_url: https://github.com/di3go-sona/tshoot
repo_name: di3go-sona/tshoot

theme:
    name: material
    icon:
        logo: material/library
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: white
          accent: deep purple
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: white
          accent: deep purple
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                import:
                    - https://docs.python.org/3.10/objects.inv
                options:
                    docstring_style: google

watch:
    - docs
    - tshoot

nav:
    - About: index.md
    - Reference:
        - tshoot: reference/tshoot.md
